### ISSUE TITLE
Fail to correctly validate 'anyURI'

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#12]
The validator is incorrectly rejecting the code below with the message:
Element 'document-link', attribute 'url': 'http://www.contractsfinder.businesslink.gov.uk:80/Common/View%20Notice.aspx?site=1000&lang=en&noticeid=158501&fs=true' is not a valid value of the atomic type 'xs:anyURI'.

```
<document-link url="http://www.contractsfinder.businesslink.gov.uk:80/Common/View%20Notice.aspx?site=1000&amp;lang=en&amp;noticeid=158501&amp;fs=true" format="text/html">
    <title>Contract: DFID: Public Financial Management Consultancy Support Uganda</title>
    <category code="A11">Contract</category>
  </document-link>
```

Suspect this is an internal problem with XMLReader or libxml or something.

Thanks to John Adams for reporting.

**Comment by Bjwebb** [comment]
There's now a patch upstream: https://bugzilla.gnome.org/attachment.cgi?id=296815&action=diff

I've tested it, and it works correctly on the DFID files we were using before.

This is no longer directly relevant to us, as I closed this issue by not using the streaming mode of libxml2. However, it's useful to keep track of this fix if we want to use streaming mode in future.
