### ISSUE TITLE
Make validation failure information more informative

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Public-Validator#18]
When a file doesn’t validate against the schema, is there a way of getting more/more simply worded info?  The ‘Extra info’ is useful, but only up to a point.  Could we mark up in red in the xml where the problems are, for example?  And put the info about where it fails into more accessible language?

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

Providing significantly improved error information will be part of this project.
