### ISSUE TITLE
Warn of upload limit

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#23]
Currently the tool does not warn users that there is an upload limit for files. And also for files pulled across the web.

**Comment by caprenter** [comment]
Something minor has been implemented in the commit above - but it could probably be improved upon.
However, long term plans for this application are still thought to involve a re-write, so this should be implemented as part of that design

**Comment by hayfield** [comment]
@dalepotter Is this a fix that should be deployed as an interim measure?
