### ISSUE TITLE
Add support for codelists

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Public-Validator#31]

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

Content checking (including Codelists) is part of this project.
