### ISSUE TITLE
Logging failed pastes

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#4]
I don't think the application is logging pasted code that fails well formed tests correctly. Needs investigation

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

Reworking logging will be part of this project.
