### ISSUE TITLE
Validation report - activity id

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Public-Validator#40]
When a file does not validate, it would be useful to also print which activity the issue occurs within , alongside the line number of the file

**Comment by hayfield** [comment]
This is similar to #18 

As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

Providing significantly improved error information will be part of this project.
