### ISSUE TITLE
Validator breaks without (user facing) error message on large files

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Public-Validator#44]
On the server the error is:

```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 76696006 bytes) in /home/iatiuser/validator.iatistandard.org/functions/fetch_data_from_url.php on line 25, referer: http://validator.iatistandard.org/index.php
```

**Comment by hayfield** [comment]
A full fix will not be implemented before the work related to the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720).

This is also closely related to #23, as such this is being closed to reduce the number of similar open issues.
