### ISSUE TITLE
Improving rulesets page

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Public-Validator#47]
- [ ]  Put in bold the first mention of an activity-id on the activities page
- [ ] Support organisation files
- [ ] Link from an activity in the summary to the detailed information about it

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

Content checking (including Rulesets) is part of this project.
