### ISSUE TITLE
Schema validation results - group by activity

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Public-Validator#58]
As per the ruleset tests, it would be useful to group schema tests and results per activity

**Comment by hayfield** [comment]
Am marking this as a consideration for Error Handling.

The Consideration is that errors and warnings should be grouped by activity.

**Comment by stevieflow** [comment]
For reference, we developed/implemented this type of behaviour on CoVE (https://github.com/OpenDataServices/cove).  See
