### ISSUE TITLE
Add tests for filesize issues

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#78]
Currently we don't have anything in place to check how the application deals with very large files.
See also: https://github.com/IATI/IATI-Public-Validator/issues/44

**Comment by hayfield** [comment]
A full fix will not be implemented before the work related to the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720).

This is also closely related to #23, as such this is being closed to reduce the number of similar open issues.
