### ISSUE TITLE
Semi permalinks

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#8]
Semi permalinks from the 'share these result' link currently send someone to the home page with the file recognised.

We could send people directly to test results (i.e. add ?test=xxx into the url).

Currently this causes problems with the left hand navigation as some of it is shown only when we know e.g. that a file is wellformed (and it might not be)

Needs some thought.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

Use of (semi-)permalinks will need to be considered as part of this project.
