### ISSUE TITLE
Rewrite the Validator completely

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#81]
The future of the validator lies in a re-write.

Users should be able to submit a file and get a summary report without having to click through each step. This requires thought and testing.

Additionally, since this was first written there are more tests out there that could be incorporated - such as the IATI stats, used in the dashboard. 

Ruleset integration, checking valid codelist values, and so on could also form part of a new tool.

Bolting these things onto the current application is probably false economy.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI.

**Comment by hayfield** [comment]
Marked this as a consideration since it lays out a number of features that should be added in a clear manner.
