### ISSUE TITLE
Add tests for the $_GET variables

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Public-Validator#89]
Recent bug; https://github.com/IATI/IATI-Public-Validator/issues/85 was because I accidentally changed the id on a form element that is read in as a $_GET variable

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

`$_GET` variables will no longer be a thing here.
