### ISSUE TITLE
IATI Validator Paste XML Function always shows invalid XML

### ISSUE THREAD

**Issue by ChrisBrooks1987** [IATI/IATI-Public-Validator#93]
I have found that when I upload or fetch from the web the same XML file it the results will be the same. However, when I then paste the very same XML into the paste facility in the Validator it will return an "invalid XML" message.

**Comment by hayfield** [comment]
Without an example, it is not possible to locate the source of this bug.

As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Public Validator is to be migrated into a combination of a library module, REST API and web UI. 

As part of this, there will be a sufficiently large test suite to catch any problems like this. The test suite will also be easily extensible to catch regressions or problems that were not caught initially.
